[project]
name = "esercizio_crewai"
version = "0.1.0"
description = "esercizio-crewai using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.165.1,<1.0.0"
]

[project.scripts]
esercizio_crewai = "esercizio_crewai.main:run"
run_crew = "esercizio_crewai.main:run"
train = "esercizio_crewai.main:train"
replay = "esercizio_crewai.main:replay"
test = "esercizio_crewai.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
