name: Python CI
on:
    push:
        branches:
            - main
            - "releases/*"
    pull_request:
        branches:
            - main
            - "releases/*"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: "Set up Python"
              uses: actions/setup-python@v5
              with:
                  python-version-file: ".python-version"

            - name: Install uv
              uses: astral-sh/setup-uv@v6

            - name: Install dependencies
              run: uv sync --locked --all-extras --dev

            - name: Verifica formattazione con Black e isort
              run: |
                  uv run black --check .
                  uv run isort --check-only .

            - name: Run tests
              run: |
                  uv run pytest --cov=src --cov-report=html
